### ISSUE TITLE
Depfu commiting with unclaimed email address

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#10]
Depfu committed as bot@depfu.com which is not registered with the Depfu account, hence Depfu is not showing up as a committer to the repository :-(

See: https://github.com/leoarnold/puppet-cups/commit/b7948e6630286529839b4dd32d4f5bb4a7b639dc

**Comment by theflow** [comment]
Yeah, I've just changed that as a workaround for #7. Actually the depfu[bot] wasn't showing up as a contributor before either, looks like GitHub always excludes bot accounts from that.

Do you run into any other issues with Depfu using an unrecognized author?

**Comment by leoarnold** [comment]
Oh, interesting, I thought it showed up as a contributor before when it was using the noreply email address - but it didn't. Sad, but not an issue.
