### ISSUE TITLE
How to deal with Bundler version requirements?

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#11]
In my `Gemfile` I require Bundler to have at least v1.16.0 because previous versions of Bundler ran endlessly, failing to solve the dependency puzzle (heuristics were not good enough to handle dependency monsters like `beaker-rspec`).

Now Depfu evidently runs on Bundler v1.15.2: https://github.com/leoarnold/puppet-cups/pull/34

What is the recommended way to deal with this? I'd hate to see Depfu suffer the same infinite spinning issues I had.

**Comment by greysteil** [comment]
@halfbyte / @theflow - we handle this at Dependabot [here](https://github.com/dependabot/dependabot-core/blob/master/lib/bundler_definition_bundler_version_patch.rb). You definitely want to be using Bundler v1.16 - it's got all the resolver improvements I wrote for the Bundler team!

**Comment by theflow** [comment]
@leoarnold We had some monkey patches in place to prevent the issue, but now we also have a proper solution to work with different Bundler version requirements. Thanks for reporting!
