### ISSUE TITLE
Rethinking the dependencies badge

### ISSUE THREAD

**Issue by theflow** [depfu/feedback#12]
Let us know any feedback and ideas about our [proposal for a new dependencies badge](https://depfu.com/blog/rethinking-the-dependencies-badge).

Try the new badge quickly by pasting your gemspec in our [preview tool](https://depfu.com/badge-preview).

**Comment by jrochkind** [comment]
I think you have a good idea, and agree that the implied insistence on all dependencies being the latest at any given time is both unrealistic and counter-productive.  There are often quite reasonable and good reasons not have 100% of your dependencies being the very latest release.  Yet on the other hand, the generate state of dependency up-to-date-ness is a useful signal in evaluating software.  I like that you are trying to find a better way to communicate this signal, hard to say how will it will succeed without seeing it in practice.

**Comment by theflow** [comment]
@jrochkind thanks for the input!

I'm also curious about pursuing the score, but I was thinking it would lead towards somehow scoring the health of the library itself: is it well maintained, how many releases, open bugs, along those lines.

**Comment by bquorning** [comment]
I looked at https://github.com/jaredbeck/libyear-bundler recently – it will tell you “how out-of-date your Gemfile is, _in a single number_”. A number like that (perhaps divided with the total number of gems in the application being checked) might be useful in your dependency badge.

Just ensure it works with private gem servers too, which I think libyear-bundler doesn’t. 😉

**Comment by theflow** [comment]
Thanks @bquorning, I didn't know about libyear, that's a very interesting approach.

**Comment by thisismydesign** [comment]
Additionally it would be great to have badges per branch. I.e. development and release branches might differ a lot.
