### ISSUE TITLE
API (for badges)

### ISSUE THREAD

**Issue by AlexWayfer** [depfu/feedback#13]
Hello!

It'll be cool to see Depfu badges in https://shields.io/

But this project need Depfu API for this: https://github.com/badges/shields/issues/1523#issuecomment-368235971

Thank you.

**Comment by theflow** [comment]
Hi Alex,

thanks, I'll have a look soon, should be easy to add.

- Florian

**Comment by theflow** [comment]
This is done now

**Comment by AlexWayfer** [comment]
Thank you!
