### ISSUE TITLE
depfu notoriously changes the order of GIT sources in Gemfile.lock

### ISSUE THREAD

**Issue by januszm** [depfu/feedback#16]
For some reason `depfu` changes the order of entries in the Gemfile.lock, compared to how the local bundler sorts them. The changes are in the GIT section:

```diff
-GIT
-  remote: https://github.com/some/gem.git
    ...
 GIT
   remote: https://NOT_GITHUB ...
+GIT
+  remote: https://github.com/some/gem.git
    ...
```

around a gem from a source other than Github (see above, in the middle, untouched in the diff).

The local bundler sets this source first, while `depfu` sets it as the last (after the gems from github.com).

The above diff is a result of running the `bundle` command locally, after a PR by `depfu` has been merged.

**Comment by theflow** [comment]
Hi @januszm, thanks for reporting this. Can you tell me what repo you're seeing this on? If it's a private repo you can also email me at hi@depfu.com

**Comment by januszm** [comment]
It's a private repository. Let's follow-up via e-mail

**Comment by theflow** [comment]
closing this since it's a special case handled via email
