### ISSUE TITLE
Wrong version conventions

### ISSUE THREAD

**Issue by mfbmina** [depfu/feedback#19]
Acording semvem (https://semver.org/) the version conventions are:

x.y.z, where:

- x: major
- y: minor
- x: patch

Depfu is calling minor updates as major. Eg: `[ruby] Update mysql2: 0.4.10 → 0.5.2 (major)`

**Comment by theflow** [comment]
Hi @mfbmina,

we actually had some feedback in the opposite direction and changed it. The truth is pre-1.0.0 there aren't a lot of rules :)

From our experience most library authors treat `minor` version jumps as `major` updates when they are pre 1.0.0. I think you can also see that here if you look at the release notes for mysq2 0.5.0 which has a lot of breaking changes: https://github.com/brianmario/mysql2/releases/tag/0.5.0

**Comment by mfbmina** [comment]
Hello! 

I assume that I did not read the mysql release tag before creating this ticket. So, how Depfu see the diferences between major, minor and patch>

**Comment by theflow** [comment]
We do it exactly as you posted for everything **after** a 1.0.0 release. For everything still in the 0.x.x range semver states:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So we treat `0.4.0` -> `0.5.0` as a major update, since that what it is in most cases.

**Comment by mfbmina** [comment]
Thanks for the reply and the explanation. Also thanks for Depfu, it is an awesome product. 😄
