### ISSUE TITLE
Run on multiple branches

### ISSUE THREAD

**Issue by Ana06** [depfu/feedback#20]
Currently Depfu can't run on multiple branches. It would be nice to be able to enable that Depfu send PRs for security updates in some branches. :pray: 

There are already some other services like https://dependabot.com which already support this. :eyes:

**Comment by theflow** [comment]
Hi @Ana06, thanks for the feedback!

Can you explain the use case a little bit more? What are these other branches used for? Are they long-lived branches used for old release lines or something like that?

thanks,
Florian

**Comment by dmarcoux** [comment]
Hi @theflow

I work with @Ana06 and we indeed want to use Depfu to keep updating old releases (especially for security updates). Is this possible with Depfu?

**Comment by Ana06** [comment]
@theflow thanks for the fast answer! As @dmarcoux says, in [Open Build Service](https://github.com/openSUSE/open-build-service) we have branches for every release and we want to use depfu for security updates in every branch as long as we stop maintaining that release version. :wink:

**Comment by theflow** [comment]
I think we have everything to make to work, but not exposed in the interface. Could you send me the repo name and the branches you want it on via mail to florian@depfu.com. Then we can try it out.

**Comment by dmarcoux** [comment]
This is the repository: https://github.com/openSUSE/open-build-service

The branches: `2.8` and `2.9`

**Comment by dmarcoux** [comment]
We are having an issue now that we run Depfu on multiple branches. The Depfu badge doesn't point to the Depfu dependencies page of the current branch. You can see it in our [README.md](https://github.com/openSUSE/open-build-service/blob/master/README.md).

So what I expect is that when I'm on `master` in the GitHub UI, the Depfu badge points to the Depfu dependencies page for `master`. When I am on `2.8` or `2.9`, it points to the respective Depfu dependencies page. For all other branches, it could point to `master`.

**Comment by theflow** [comment]
Sorry for that, that was my fault. It's fixed now for your existing badge on master.

To get the correct badge for a branch, you have to link up the specific badge you can get from the Depfu dashboard for that branch. I don't think there is any way for us to detect that automatically.

**Comment by dmarcoux** [comment]
No worries! Thanks for the quick reply.
