### ISSUE TITLE
@depfu[bot] rebase doesn't work

### ISSUE THREAD

**Issue by Ana06** [depfu/feedback#23]
Github autocomplete suggests to use @depfu[bot]:

![image](https://user-images.githubusercontent.com/16052290/45949845-ad4dfa80-bffd-11e8-9187-a1888ff333e4.png)

But it seems like `@depfu[bot] rebase` don't work, while `@depfu rebase` does work. It would be nice that `@depfu[bot] rebase` also work as it is confusing with the autocomplete. :wink: 

![image](https://user-images.githubusercontent.com/16052290/46547935-d60fa300-c8cd-11e8-8e54-51ba763bd903.png)

**Comment by theflow** [comment]
Thanks for the feedback @Ana06!

I've added support for that now, so it should work! Github behaves a bit strange, I haven't quite figured out when it actually puts `@depfu[bot]` into the autocomplete, it's not always there.

**Comment by Ana06** [comment]
Thanks @theflow! :cupid: It seems to work :wink:
