### ISSUE TITLE
Scope of "7 PRs at once"

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#24]
Depfu.com says

>We drip-feed you updates if you're behind, but never open more than 7 PRs at once to not overwhelm you.

I was wondering about the scope of this claim. Is it per day? Per repository? Or maybe per GitHub account, so I might miss out on updates if I don't pay attention those 7 open PRs in that one company repository nobody actually cares about anymore :wink:

**Comment by theflow** [comment]
Hi @leoarnold 

The PR limit is per repo, or if you have multiple folders or languages in the same repo the limit is scoped to those. So you can happily ignore certain parts, and will still get new PRs in active repos. Also security updates will always ignore the PR limit.

Does that make sense?

**Comment by leoarnold** [comment]
@theflow Absolutely, matches my intuitive associations, thanks!
