### ISSUE TITLE
Necessity for joint update not detected.

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#25]
No problem or feature request here, just wanted to let you know in case you'd consider this a bug:

Depfu upgraded to `beaker-puppet` v1.7.0

https://github.com/leoarnold/puppet-cups/pull/66/files

and builds failed because `beaker-puppet` v1.7.0 depends on  `beaker ~> 4.1` which was not upgraded. That upgrade was suggested independently

https://github.com/leoarnold/puppet-cups/pull/65/files

but the two PRs were not linked as usual - probably because this project does not use a `Gemfile.lock` for technical reasons.

**Comment by theflow** [comment]
Closing older issues
