### ISSUE TITLE
Badges incongruent about dependency count

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#26]
No issue, just FYI: In a Depfu PR today I noticed

![screenshot_20190123_113131](https://user-images.githubusercontent.com/4201235/51600658-c65ead80-1f02-11e9-9752-d584d8b06f7c.png)

while the repository shows

![screenshot_20190123_113150](https://user-images.githubusercontent.com/4201235/51600703-dc6c6e00-1f02-11e9-9ef2-d14aba997245.png)

The number of outdated dependencies seems to be accurate but the total dependency surely did not drop by 32 over a `rubocop` upgrade.

Does one display the total dependency count whereas the other only counts dependencies from the `:default` group?

**Comment by theflow** [comment]
Yeah, the public badge only counts runtime dependencies as that's the default what other badge services do as well. The number in the PR is all direct dependencies, including development/test etc.

I understand that's a bit confusing, but these badges serve different purposes, so not quite sure what a good solution would be.
