### ISSUE TITLE
Grouped Updates release notes

### ISSUE THREAD

**Issue by klyonrad** [depfu/feedback#31]
One thing I like most about depfu's pull requests is the **instant** access to the release notes. The Pull Request of grouped updates only gives a link to the changelog 😢 

At least that's what I have seen for grouping of dev and indirect dependencies

**Comment by theflow** [comment]
Hi @klyonrad 👋

Yeah, the problem is that we're hitting the limit of a pull request body if there are too many packages. I'm working on showing all the details if it fits, but not sure we can show it in all cases.
