### ISSUE TITLE
My github handle was mentioned in the changelog of next.js

### ISSUE THREAD

**Issue by Janpot** [depfu/feedback#32]
My github handle was mentioned in the changelog of next.js. Now I'm being notified and subscribed to all issues opened by your bot for this version, on repositories I have nothing to do with.
Maybe you can just link to the changelogs instead of inlining them, or sanitize them in some way?

Same issue as https://github.com/greenkeeperio/greenkeeper/issues/1113

**Comment by theflow** [comment]
Ah, damn, really sorry about that @Janpot. We do sanitize but it didn't catch the case here: https://github.com/zeit/next.js/releases/tag/v9.0.0 where some usernames are not linked on the release itself. I'll look into it.

**Comment by Janpot** [comment]
If it helps: it looks like Github doesn't linkify user handles when there's more than 50.

**Comment by theflow** [comment]
Yeah. I've fixed it manually for now on that release, so you shouldn't get any further subscriptions (but unfortunately most of the PRs got created already). I'll work on better detection for this case so it doesn't happen in the future.
