### ISSUE TITLE
Grouped Updates: rails-i18n

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#34]
I really like your grouped update feature for `rails`. Would it be possible to include `rails-i18n` if the project uses the gem? Because those Depfu upgrades seem to cause mutual conflicts as of now:

![Screenshot_20190920_114201](https://user-images.githubusercontent.com/4201235/65317835-d5ceed00-db9c-11e9-8f3e-0e98e39d9796.png)

**Comment by theflow** [comment]
Hi @leoarnold, good idea! While it's not technically the same group since there is not always a corresponding version for each Rails release. I've added it now and it should help conflicts on Rails major version upgrades.

**Comment by leoarnold** [comment]
:clap: 33 minutes from initial report to fix deployed is beyond any SLA
