### ISSUE TITLE
Yarn workspace support

### ISSUE THREAD

**Issue by Siilwyn** [depfu/feedback#37]
Would be great to get Yarn workspace support, is there any ETA? Depfu is not OS is it? Otherwise I would create a PR.

**Comment by theflow** [comment]
Hey @Siilwyn 👋

Thanks for the input, it's on our list and we should get to it quite soon. I'll let you know!

**Comment by Siilwyn** [comment]
Alright cheers! Eagerly waiting for this to land. :)

**Comment by theflow** [comment]
Hey @Siilwyn: we've shipped a first version of this and it's looking good so far. Would be great to get your input on if this works as you expect it.

**Comment by Siilwyn** [comment]
:clap:  Looks good! Only I can't find how to delete the 'npm' context of the project since I switched to yarn it isn't needed anymore. But I guess that would be a new separate feature.

Will close this and report here if I find strange behavior.

**Comment by theflow** [comment]
@Siilwyn We're actually working on that right now unrelated to this feature, but I've cleaned it up for you manually now.
