### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by FranklinYu** [depfu/feedback#4]
For example:
 - JavaScript (npm) or they would use [David](https://david-dm.org/).
 - Python (PyPI) or they would use [Requires.IO](https://requires.io/).

If Depfu is Ruby-only, it is not as outstanding since there is also [Deppbot](https://www.deppbot.com/).

**Comment by franklinyu** [comment]
Bump.

**Comment by theflow** [comment]
Closing this in favor of a more general issue: https://github.com/depfu/feedback/issues/38
