### ISSUE TITLE
Unwanted downgrade

### ISSUE THREAD

**Issue by romanlehnert** [depfu/feedback#5]
Given a Gemfile with only therubyracer included like [this one](https://github.com/givve/depfu-update-downgrade-bug/blob/aa5fa4c7eefe2c9e2ad8c6330ccdbe80d577f316/Gemfile) and the corresponding [Gemfile.lock](https://github.com/givve/depfu-update-downgrade-bug/blob/aa5fa4c7eefe2c9e2ad8c6330ccdbe80d577f316/Gemfile.lock).

Currently, the most recent version of therubyracer (0.12.3) depends on libv8 (~> 3.16.14.15).
Actually, therubyracer removed its dependency with version 0.11.0 and reintroduced it with 0.11.1.

However, depfu proposes to major upgrade libv8 to 6.3.292.48.1 by downgrading therubyracer to minor 0.11.0. 

Is this intended behaviour?

This is a copy of the PR in our repo. I'll try to reproduce the behavior in a separate [repo](https://github.com/givve/depfu-update-downgrade-bug):

-----------------------

We've updated a dependency and here is what you need to know:

| gem name | version specification | old version | new version |
| --- | --- | --- | --- |
| libv8 | _indirect dependency_ | 3.16.14.19 | 6.3.292.48.1 |

To resolve a dependency conflict, the update changed a few other dependencies as well:

| action | gem name | old version | new version |
| --- | --- | --- | --- |
| removed | libv8 | 3.16.14.19 | |
| updated | therubyracer | 0.12.3 | 0.11.0 |

You should probably take a good look at the info here and the test results before merging this pull request, of course.

#### ↗️ libv8 (_indirect_, 3.16.14.19 → 6.3.292.48.1) · [Repo](http://github.com/cowboyd/libv8) · [Changelog](https://github.com/cowboyd/libv8/blob/master/CHANGELOG.md)

<details>
<summary>Commits</summary>
<p><a href="https://github.com/cowboyd/libv8/compare/d8b962fdb3a900c4ac0d7335fbcc2ee9e2d7fa2e...17b93fd52fae6c0163c5e8e930255caeee76f680">See the full diff on Github</a>. The new version differs by 1 commit:</p>

<ul>
<li><a href="https://github.com/cowboyd/libv8/commit/17b93fd52fae6c0163c5e8e930255caeee76f680"><code>binary release basis v6.3.292.48.1</code></a></li>
</ul>
</details>

#### ✳️ therubyracer (0.12.3 → 0.11.0) · [Repo](http://github.com/cowboyd/therubyracer) · [Changelog](https://github.com/cowboyd/therubyracer/blob/master/Changelog.md)

<details>
<summary>Commits</summary>
<p><a href="https://github.com/cowboyd/therubyracer/compare/a635aee79b2057c396f8af92417cadf93415c275...040bcf3c84b11fc02d14bea4bfe9f2481da47bc6">See the full diff on Github</a>. The new version differs by more commits than we can show here.</p>
</details>

**Comment by theflow** [comment]
Thanks for reporting this, Roman!

Since therubyracer removed the lib8 dependency temporarily, Bundler things that those are valid versions to satisfy the `libv8 ~> 3.16.14.15` requirement, which is technically true, but not really expected behavior :)

I'll investigate if running with `BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS` is an option for Depfu. In this case it would produce  a conflict, which is correct, but I have to check if it has any downsides in other scenarios.

**Comment by theflow** [comment]
We're running with `BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS` for everyone now as we feel that's what everyone expects and it will also be the default in Bundler 2.

**Comment by romanlehnert** [comment]
👍

**Comment by leoarnold** [comment]
@theflow We have observed several PRs with downgrades (down to v0.1.0 for some gems) now. Is `BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS` still in place?

**Comment by theflow** [comment]
yeah, I noticed that as well, I think it's a bug in Bundler 1.16. I'll have a look at it this week.

**Comment by theflow** [comment]
This has been fixed for a while now.
