### ISSUE TITLE
Outstanding Update PRs

### ISSUE THREAD

**Issue by klausmeyer** [depfu/feedback#6]
Hi,

first of all I want to say thank you for this great project

I really love the idea and have already merged a bunch of PRs in one of my open source side-projects (https://github.com/klausmeyer/docker-registry-browser).

I have two short questions:

* Currently I'm waiting for a PR for the upgrade from bootstrap `4.0.0.beta2.1` to `4.0.0.beta3` which is already released a week ago - is anything blocking the update on your side?
* Why is depfu only taking care of gems mentioned in the `Gemfile` itself and not all of the possible updates? See the following output of `bundle update`:

<details>

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 53fab5f..205c5fc 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -41,10 +41,10 @@ GEM
     addressable (2.5.2)
       public_suffix (>= 2.0.2, < 4.0)
     arel (8.0.0)
-    autoprefixer-rails (7.1.6)
+    autoprefixer-rails (7.2.4)
       execjs
     bindex (0.5.0)
-    bootstrap (4.0.0.beta2.1)
+    bootstrap (4.0.0.beta3)
       autoprefixer-rails (>= 6.0.3)
       popper_js (>= 1.12.3, < 2)
       sass (>= 3.5.2)
@@ -76,7 +76,7 @@ GEM
     faraday_middleware (0.12.2)
       faraday (>= 0.7.4, < 1.0)
     ffi (1.9.18)
-    globalid (0.4.0)
+    globalid (0.4.1)
       activesupport (>= 4.2.0)
     hashdiff (0.3.7)
     i18n (0.9.1)
@@ -96,21 +96,18 @@ GEM
     loofah (2.1.1)
       crass (~> 1.0.2)
       nokogiri (>= 1.5.9)
-    mail (2.6.6)
-      mime-types (>= 1.16, < 4)
+    mail (2.7.0)
+      mini_mime (>= 0.1.1)
     method_source (0.9.0)
-    mime-types (3.1)
-      mime-types-data (~> 3.2015)
-    mime-types-data (3.2016.0521)
     mini_mime (1.0.0)
     mini_portile2 (2.3.0)
-    minitest (5.10.3)
+    minitest (5.11.1)
     multi_json (1.12.2)
     multipart-post (2.0.0)
-    nio4r (2.1.0)
+    nio4r (2.2.0)
     nokogiri (1.8.1)
       mini_portile2 (~> 2.3.0)
```
</details>

<br>In the Web-UI of depfu everything is displayed as "up-to-date".

Best, Klaus

**Comment by theflow** [comment]
Thanks for the feedback, Klaus!

 * We're not updating to any kind of pre-releases right now. Would you want that for all of your gems or only certain ones?
 * Yeah, indirect dependencies is something we're working on right now. We're a bit worried about the amount of pull requests it would create, but we're testing various ideas around that. If you want to help test it, send me an email to florian@depfu.com

- Florian

**Comment by klausmeyer** [comment]
Hi Florian,

thanks for your response.

> We're not updating to any kind of pre-releases right now.

Makes sense. Did I overlook it in the documentation?
If not it would be a good point to add 😁 

> Would you want that for all of your gems or only certain ones?

For me it would be fine to get PRs for gems which I'm already referencing with a prerelease in my `Gemfile` (`gem 'bootstrap', '~> 4.0.0.beta'` in my case).

> Yeah, indirect dependencies is something we're working on right now. [...]
> If you want to help test it, send me an email [...]

Sure. I wouldn't mind to support there. Will contact you after some consideration 🤓

Best Klaus
