### ISSUE TITLE
Avatar image for depfu bot

### ISSUE THREAD

**Issue by neumayr** [depfu/feedback#7]
Currently, the depfu bot didn't have a image. 
Would be nice to see an image here.

Thank you for building this service 👏  👏

![screen shot 2018-01-11 at 16 49 46](https://user-images.githubusercontent.com/13056188/34833399-9077e308-f6ef-11e7-8625-cfc32056b1eb.png)

**Comment by theflow** [comment]
Thanks for reporting this! Unfortunately it’s a bug on GitHub’s side and we have to wait for them to fix it. I’ll try to follow up with them again as it also annoys me quite a bit :)

**Comment by leoarnold** [comment]
@neumayr Looks like this is solved:
![screenshot_20180126_111202](https://user-images.githubusercontent.com/4201235/35435124-d1776a04-0289-11e8-9eb0-4d74b28c4b2c.png)

**Comment by neumayr** [comment]
@leoarnold Nopey, for example in the commit timeline it's missing
https://github.com/fidor/fidor_api_demo/commits/master

**Comment by theflow** [comment]
Ok, I've found a workaround for this issue that will work until GitHub rolls out a real fix. It will show up for all new PRs from now on (or any rebases).
