### ISSUE TITLE
Links to a gem's repo and changelog on Depfu summary page

### ISSUE THREAD

**Issue by leoarnold** [depfu/feedback#9]
It would be nice to have links to each gem's repo and changelog on the https://depfu.com/repos/user/repo page.

**Comment by theflow** [comment]
Good idea, Leo!

I've deployed a first version of this today. I might have to play around with the design a bit more, since it feels a bit busy now, but the links are all there :)

**Comment by leoarnold** [comment]
Awesome, thanks!
